### ISSUE TITLE
can this work with html?

### ISSUE THREAD

**Issue by purplecones** [t9md/atom-vim-mode-plus-keymaps-for-surround#1]
First, thanks so much for all these great plugins. I use most of them daily.

A question I have for surround is if its possible to remove/change surrounding html elements. Currently, using `c s` with html changes the angle brackets.

**Comment by t9md** [comment]
No.  Not supported.
For tag manipulation currently supported is, `i t`, `a t` text-object by vim-mode-plus core.
This is just keymap providing plugin. If you want any functionality, report to vim-mode-plus's issue.

Here is example( maybe what you want is different I think ) of `i t` and `a t`.
- Keystroke of 1st transaction: `c i t hello`
- Keystroke of 2nd transaction: `d a t`
![i-t-text-obj](https://cloud.githubusercontent.com/assets/155205/23559825/9e36f2ce-007b-11e7-9c4a-989aa510a054.gif)

**Comment by purplecones** [comment]
Thanks @t9md. I'm still learning many of the vim shortcuts but familiar with those keystrokes and use them all the time when editing HTML 😄 .

Using your example, I'm specifically looking for a way to change `<abc>` and `</abc>` quickly.

I know this is not currently available, but what if there was a keystroke `c s t div` that makes this
```html
<abc>
 <title>hello</title>
</abc> 
```
turn into this
```html
<div>
 <title>hello</title>
</div> 
```

Is this possible?

**Comment by purplecones** [comment]
I see the exact issue [here](https://github.com/t9md/atom-vim-mode-plus/issues/381). Will close this but would be helpful to have that ability.
