### ISSUE TITLE
Surrond-Keymapping is not shown in atom’s keymap view

### ISSUE THREAD

**Issue by Semnodime** [t9md/atom-vim-mode-plus-keymaps-for-surround#2]
Atom’s keymap view
![](https://cloud.githubusercontent.com/assets/19511852/25625886/0866d2de-2f5e-11e7-89d3-fab8cc19954f.png) filtered for the surround keymapping.

Hi,
I want to edit the keymapping for the surround in visual mode (currently shift-S) and wondered why the according binding does not show up. Can you help me?

Thanks,
Semno

**Comment by Semnodime** [comment]
After I pasted your config, everything worked as supposed to.

**Comment by t9md** [comment]
Read README.md. There is also surround-keymap package.

**Comment by t9md** [comment]
What the config? If keymap not appear, it's bad.
This package's config should be available without any user's configuration.

**Comment by t9md** [comment]
<img width="1409" alt="settings_ ___github_tree-view" src="https://cloud.githubusercontent.com/assets/155205/25627142/9ff244f6-2f9c-11e7-999c-badf5da77554.png">

This is screen shot of mine. **Source** field indicates where each keymap definition comes from.
User is user's `keymap.cson`. And look this package's keymaps is in the list.

**Comment by Semnodime** [comment]
Thanks for the fast respose! The problem seems to have quietly disappeared:
![grafik](https://cloud.githubusercontent.com/assets/19511852/25702368/fbea4a3a-30d0-11e7-8c05-a2ed40c1f715.png)
You can reclose the issue as I cannot reproduce it.

**Comment by t9md** [comment]
Ok!
