### ISSUE TITLE
Using `S{` on visual selection acts the same as `S}` 

### ISSUE THREAD

**Issue by prodeniser** [t9md/atom-vim-mode-plus-keymaps-for-surround#3]
If I'm not mistaken, the close brace is supposed to add surrounding braces with a space included around the visual selected content. Is there a way to implement this? Or am I perhaps doing the motion wrong.

**Comment by t9md** [comment]
Read README.md, this is just keymap, feature is provided by vim-mode-plus core.
You can customize what chars adds extra space around surround char in vim-mode-plus's setting.
Find setting shown on following GIF and setting same value make it behave in same way of surround.vim.

<img width="558" alt="settings_ ___github_atom-vim-mode-plus" src="https://user-images.githubusercontent.com/155205/38003159-3ad7e278-3271-11e8-9d28-e16c9d6141e6.png">

**Comment by prodeniser** [comment]
Ah, thank you, apologies.
