### ISSUE TITLE
Auto detect switch

### ISSUE THREAD

**Issue by idoo** [t9md/atom-vim-mode-plus-keymaps-for-surround#4]
Thank you for this plugin, my life became better <3

I have a question because my finger feeling smarter that my brain — is it possible to disable auto detect for surround?

**Comment by t9md** [comment]
You can uninstall this package, then copy and paste to your keymap.cson from the file below for only the keymaps you need.

https://github.com/t9md/atom-vim-mode-plus-keymaps-for-surround/blob/master/keymaps/vim-mode-plus-keymaps-for-surround.cson

**Comment by idoo** [comment]
@t9md btw, why it's not part of `vim-mode-plus` ?

**Comment by t9md** [comment]
Are you asking ‘why this keymap for surround is not provided directly in vmp?’

Since this pkg define `s` starting keymap, but `s` is for native `substitute` command.
I think overwriting `s` as default with surround keymap is rude.
So I’m providing keymap only pkg as separate pkg.
